image: rust:latest

stages:
  - build
  - test

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/cargo"

cache:
  paths:
    - ./target
    - cargo

build_job:
  stage: build
  script:
    - rustc --version
    - cargo build --verbose
  artifacts:
    paths:
      - target/

test_job:
  stage: test
  script:
    - git submodule update --init
    - cargo test --verbose -- --nocapture
