name: Rust

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        git submodule update --init --recursive
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Validate XML
      run: |
        apt-get update
        apt-get install -y libxml2-utils
        ./validate.sh
